In [2]:
import os
import tensorflow as tf

# MNIST 데이터셋 로드
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 데이터 정규화
x_train, x_test = x_train / 255.0, x_test / 255.0

# 모델 정의
mlp_model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 모델 컴파일
mlp_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 모델 훈련
mlp_model.fit(x_train, y_train, epochs=5)

# HDF5 형식으로 모델 저장
os.makedirs("./mlp_model", exist_ok=True)
mlp_model.save("./mlp_model/mlp_model.h5")  # HDF5 형식으로 저장

# TFLite 모델로 변환 (HDF5 모델 사용)
converter = tf.lite.TFLiteConverter.from_keras_model(mlp_model)
tflite_model = converter.convert()

# TFLite 모델 저장
with open('./keras_model.tflite', 'wb') as f:
    f.write(tflite_model)

# HDF5 모델 로드
h5_model = tf.keras.models.load_model("./mlp_model/mlp_model.h5")

# TFLite 모델로 변환 (HDF5 모델 사용)
converter = tf.lite.TFLiteConverter.from_keras_model(h5_model)  # HDF5 모델을 사용
tflite_model_h5 = converter.convert()

# TFLite 모델 저장
with open('./saved_model.tflite', 'wb') as f:
    f.write(tflite_model_h5)

class Inc(tf.keras.layers.Layer):
    def call(self, inputs):
        return inputs + 1
inc = Inc()

class Inc_Graph(tf.keras.layers.Layer):
    @tf.function
    def call(self, inputs):
        return inputs + 1
inc_g = Inc_Graph()

inc_g2 = tf.function(inc)

print(inc_g(tf.constant(3)))
print(inc_g(tf.constant([3, 2])))
print(inc_g(tf.constant([[3, 2], [1.0, 5.0]])))

print(inc_g2(tf.constant(3)))
print(inc_g2(tf.constant([3, 2])))
print(inc_g2(tf.constant([[3, 2], [1.0, 5.0]])))

print(inc_g(tf.constant(4)))
print(inc_g2(tf.constant(4)))

concrete_fun = inc_g.call.get_concrete_function(tf.TensorSpec(shape=(1, 3),
                dtype=tf.float32))
print(concrete_fun(tf.constant([[1.0, 2.0, 3.0]])))

concrete_fun = inc_g2.get_concrete_function(tf.TensorSpec(shape=(1, 3),
                dtype=tf.float32))
print(concrete_fun(tf.constant([[1.0, 2.0, 3.0]])))

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2612 - accuracy: 0.9266
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1173 - accuracy: 0.9655
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0792 - accuracy: 0.9763
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0584 - accuracy: 0.9821
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0461 - accuracy: 0.9857


c:\Users\COMPUTER\anaconda3\envs\tf2\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


INFO:tensorflow:Assets written to: C:\Users\Public\Documents\ESTsoft\CreatorTemp\tmpmzx60qt4\assets


INFO:tensorflow:Assets written to: C:\Users\Public\Documents\ESTsoft\CreatorTemp\tmpmzx60qt4\assets


INFO:tensorflow:Assets written to: C:\Users\Public\Documents\ESTsoft\CreatorTemp\tmp9h4b0f8a\assets


INFO:tensorflow:Assets written to: C:\Users\Public\Documents\ESTsoft\CreatorTemp\tmp9h4b0f8a\assets


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)
tf.Tensor(
[[4. 3.]
 [2. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)
tf.Tensor(
[[4. 3.]
 [2. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([[2. 3. 4.]], shape=(1, 3), dtype=float32)
tf.Tensor([[2. 3. 4.]], shape=(1, 3), dtype=float32)
